# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’
# Uncomment this line if you're using Swift
#use_frameworks!

target 'BaseProject' do
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage'
    pod 'Masonry', '~> 1.0.0'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'MJExtension'
    pod 'MJRefresh'
    pod 'Reachability', '~> 3.2'
    pod 'YYKit'
    pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
    pod 'IQKeyboardManager'
end
