# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CDDBaseProject' do
    pod "AFNetworking"
    pod "SDWebImage"
    pod "Masonry"
    pod 'SVProgressHUD', :head
    pod 'MJExtension'
    pod 'MJRefresh'
    pod "Aspects"
    pod 'YTKNetwork'
    pod 'ReactiveCocoa'
end

target 'CDDBaseProjectTests' do

end

target 'CDDBaseProjectUITests' do

end

