# Uncomment this line to define a global platform for your project
# platform :ios, ‘7.0’

pod "AFNetworking"
pod "SDWebImage"
pod "Masonry"
pod 'SVProgressHUD', :head
pod 'MJExtension'
pod 'MJRefresh'
pod "Aspects"